### ISSUE TITLE
nvm install - errors

### ISSUE THREAD

**Issue by jorjik** [coreybutler/nvm-windows#334]
### My Environment

- [+] Windows 7 or below (not truly supported due to EOL - see wiki for details)
- [+] My Windows installation is non-English.

### I'm using NVM4W version:
- 1.1.6

### I have already...

- [+] read the README to be aware of npm gotchas & antivirus issues.
- [+] reviewed the [wiki](https://github.com/coreybutler/nvm-windows/wiki) to make sure my issue hasn't already been resolved.
- [+] verified I'm using an account with administrative privileges.
- [x] made sure this isn't a question about how to use NVM for Windows, since [gitter](https://gitter.im/coreybutler/nvm-windows?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge) is used for questions and comments.
- [ ] searched the issues (open and closed) to make sure this isn't a duplicate.

### My issue is related to (check only those which apply):
- A standard shell environment (terminal/powershell)

### Actual Behavior

nvm install 7.10.1
C:\Users\������\AppData\Roaming\nvm could not be found or does not exist. Exiting.
Downloading node.js version 7.10.1 (64-bit)...
Error while creating C:\Users\������\AppData\Roaming\nvm\v7.10.1\node64.exe - open C:\Users\������\AppData\Roaming\nvm\v7.10.1\node64.exe: The system cannot find the path specified.
Error while downloading https://nodejs.org/dist/v7.10.1/win-x64//node.exe - invalid argument
Complete
Creating C:\Users\������\AppData\Roaming\nvm\temp

mkdir C:\Users\������\AppData\Roaming\nvm\temp: The system cannot find the path specified.

### Steps to reproduce the problem:
install
reboot

**Comment by b-dur** [comment]
Does your user name have spaces in it? Example `C:\Users\john doe\AppData\Roaming\nvm`

**Comment by jorjik** [comment]
no (i have russian_lang)

**Comment by b-dur** [comment]
If you open this path `C:\Users\������\AppData\Roaming\` in your File Explorer, do you see the **nvm** folder?

**Comment by jorjik** [comment]
yes

**Comment by TonyRyze** [comment]
I have the same problem.How to resovel it?

**Comment by Raerten** [comment]
I guess that `������` in `C:\Users\������\AppData\Roaming\` it is ASCII representation of UTF (multibyte) characters.
may be nvm internally doesn't use multibyte string and pass to Win API wrong chars for path?

**Comment by parmentf** [comment]
Same problem, my username is `François`, and Windows does not seem to recognize the `ç` correctly, maybe somewhere in the program, it is needed to wrap the path within quotes?

In PowerShell (with admin rights):

```sh
C:\Users\Fran�ois\AppData\Roaming\nvm could not be found or does not exist. Exiting.
Downloading node.js version 10.11.0 (64-bit)...
Error while creating C:\Users\Fran�ois\AppData\Roaming\nvm\v10.11.0\node64.exe - open C:\Users\Fran�ois\AppData\Roaming\nvm\v10.11.0\node64.exe: Le chemin d’accès spécifié est introuvable.
Error while downloading https://nodejs.org/dist/v10.11.0/win-x64//node.exe - invalid argument
Complete
Creating C:\Users\Fran�ois\AppData\Roaming\nvm\temp

mkdir C:\Users\Fran�ois\AppData\Roaming\nvm\temp: Le chemin d’accès spécifié est introuvable.
```

In Git Bash:

```bash
François@FRANÇOIS-PCTOUR ~
$ nvm install latest
C:\Users\Fran�ois\AppData\Roaming\nvm could not be found or does not exist. Exiting.
Downloading node.js version 10.11.0 (64-bit)...
Error while creating C:\Users\Fran�ois\AppData\Roaming\nvm\v10.11.0\node64.exe - open C:\Users\Fran�ois\AppData\Roaming\nvm\v10.11.0\node64.exe: Le chemin d’accès spécifié est intr
ouvable.
Error while downloading https://nodejs.org/dist/v10.11.0/win-x64//node.exe - invalid argument
Complete
Creating C:\Users\Fran�ois\AppData\Roaming\nvm\temp

mkdir C:\Users\Fran�ois\AppData\Roaming\nvm\temp: Le chemin d’accès spécifié est introuvable.
```

the `nvm` directory exists, it just can't find it:

```bash
François@FRANÇOIS-PCTOUR ~
$ ls AppData/Roaming/nvm/
elevate.cmd  elevate.vbs  install.cmd  nodejs.ico  nvm.exe  settings.txt  unins000.dat  unins000.exe  unins000.msg
```

**Comment by parmentf** [comment]
After reading @JJnne's comment, I tried this:

```
PS C:\WINDOWS\system32> nvm root "C:\Users\François\AppData\Roaming\nvm"

Root has been set to C:\Users\François\AppData\Roaming\nvm
PS C:\WINDOWS\system32> nvm install latest
Downloading node.js version 10.11.0 (64-bit)...
Complete
Creating C:\Users\François\AppData\Roaming\nvm\temp

Downloading npm version 6.4.1... Complete
Installing npm v6.4.1...

Installation complete. If you want to use this version, type

nvm use 10.11.0
```

and it worked! Thanks.
But only enclosing the path in quotes!

**Comment by coreybutler** [comment]
This should be resolved in the master branch and is slated for release in 1.1.8, which I simply haven't had time to get to yet. Probably 2-3 weeks before I'll be able to cut another release.

**Comment by LorenaGitHub** [comment]
![image](https://user-images.githubusercontent.com/48281904/54425625-10e7f380-4716-11e9-876c-f0cabb0a2a41.png)
It gives me error and it does not let me install it

**Comment by rw251** [comment]
This also happens if you don't have the necessary permissions to the AppData directory. My work laptop has a weird setup where although my account appears to have admin access on AppData I can't actually copy *.exe files into it - so I get the exact error as appears in the above screenshot. It works fine if I pick a different directory when installing.

**Comment by sansa91** [comment]
> Hi guys!
> 
> I had same issue. For me cause of the problem was special characters in my windows username. I was able to fix this problem by re-setting Nvm root: `nvm root C:\Users\username\AppData\Roaming\nvm`

<3

**Comment by akfn1209** [comment]
thank you very much!!! I could solve this problem because of you

**Comment by yomeloty** [comment]
> 如果您`C:\Users\������\AppData\Roaming\`在文件资源管理器中打开此路径，您是否看到**nvm**文件夹？

没有，怎么办，自己新建新建一个吗

**Comment by coreybutler** [comment]
spaces and special characters are now supported in https://github.com/coreybutler/nvm-windows/releases/tag/1.1.8

**Comment by yoni333** [comment]
>I tried git bash and that`s solved problem. Do not use cmd, powershell and smth like that :)
@jorjik - mube you will ad this to the documantion ?

**Comment by DenisLopatin** [comment]
It's just awful. No matter what I do, I get the following message -  _The system cannot find the path specified_ ...
I use power shell, cmd, bash, reinstalling to other directories, changing the path to nvm root. WTF?

**Comment by dank-Sniping** [comment]
I am having the exact same issue and I found this workaround:
1. Install `nvm-windows` to a safe path *(such as `%programfiles%`)*
2. Move the `nvm` directory to the unsafe path *(it installs to `%appdata%` by default)*
3. Create a symlink via `mklink /d "%programfiles%\nvm" "%appdata%\nvm"` *(you may need to run as administrator)*

As you can see, I was able to install a version of `node` successfully.
![Screenshot](https://user-images.githubusercontent.com/49392266/141206161-d333c6d6-8bac-4e5a-94b7-af2035d96084.png)

**Comment by belsouza** [comment]
Hi! In my case, the installation was the same as it was shown (in the users folder), but the error was fatal - and the error message doesn't match the situation at all.
It must be something related to the user's machine or operating system. I can't even program applications with react on my machine anymore because of the forced obsolescence of the software.

![Capturar](https://user-images.githubusercontent.com/61118820/158046988-0bff4f15-1fe9-4612-8b79-a17e96a68737.PNG)

**Comment by pinkpeacher** [comment]
Thanks to you, my problem is solved.

**Comment by rmnkk** [comment]
> After reading @JJnne's [comment](https://github.com/coreybutler/nvm-windows/issues/334#issuecomment-408417447), I tried this:
> 
> ```
> PS C:\WINDOWS\system32> nvm root "C:\Users\François\AppData\Roaming\nvm"
> 
> Root has been set to C:\Users\François\AppData\Roaming\nvm
> PS C:\WINDOWS\system32> nvm install latest
> Downloading node.js version 10.11.0 (64-bit)...
> Complete
> Creating C:\Users\François\AppData\Roaming\nvm\temp
> 
> Downloading npm version 6.4.1... Complete
> Installing npm v6.4.1...
> 
> Installation complete. If you want to use this version, type
> 
> nvm use 10.11.0
> ```
> 
> and it worked! Thanks. But only enclosing the path in quotes!

Still have this problem. My user name is written using Cyrillic characters. Setting root helps. Thank you

**Comment by DenisLopatin** [comment]
@rmnkk change nvm directory. Use `nvm root`  and set root as some directory without cyrillic characters. I set it as `C:\node_versions` for example. Try it

**Comment by Ivan-Bliminse** [comment]
> 

This worked great! Thank you.
Just rename your Path when install from C:\Users\[yourNameHere]\AppData\Roaming\nvm => C:\node_versions

**Comment by dadadadaben123** [comment]
> 

thank you for your advice

**Comment by dadadadaben123** [comment]
@JJnne thank you for your advice,it works

**Comment by yoni333** [comment]
by the - there is a new alternative to NVM that already fix all of this problems it is call -- VOLTA
https://github.com/volta-cli/volta

it is also give you the ability to define in the different node js vesrsion  per folder

**Comment by devwebaleksey** [comment]
The problem was solved by the nm root command C:\Users\username\AppData\Roaming\nvm . Write your name here as in the account.

**Comment by Kakcil** [comment]
> use with " string definder

**Comment by NasDev07** [comment]
help me, why can't install node in nvm.

`$ nvm install 14.17.0
Downloading node.js version 14.17.0 (64-bit)...
Error while creating C:\Users\nvm\v14.17.0\node64.exe - open C:\Users\nvm\v14.17
.0\node64.exe: The system cannot find the path specified.
Could not download node.js v14.17.0 64-bit executable.
`

**Comment by ThanhDatwd** [comment]
> Does your user name have spaces in it? Example `C:\Users\john doe\AppData\Roaming\nvm`

how can i fix it

**Comment by escandiel** [comment]
Im with the same error, my name is "João Victor" and i already tried everything, in git bash and in cmd and everything that you guys said it i tried... 
<img width="727" alt="cmd-error" src="https://github.com/coreybutler/nvm-windows/assets/127462607/958eaf0a-a411-4849-8b7c-c1ea404d6658">
<img width="475" alt="erro-gitbash" src="https://github.com/coreybutler/nvm-windows/assets/127462607/bcba1d65-7452-4412-a904-53aae1fe7a41">

**Comment by Miho1254** [comment]
> Hi guys!
> 
> I had same issue. For me cause of the problem was special characters in my windows username. I was able to fix this problem by re-setting Nvm root: `nvm root C:\Users\username\AppData\Roaming\nvm`

thanks, this solution still works after 8 years lmao

**Comment by github-cherry** [comment]
好奇怪，本来我也是。重新打开cmd又好了，神奇
![image](https://github.com/coreybutler/nvm-windows/assets/43592730/46973612-a19f-4f11-a5b4-c79673d1f295)

**Comment by aaabigfish** [comment]
the dir needs to set permissions，I solved it
![image](https://github.com/user-attachments/assets/11591627-084f-4e96-85fa-5e68ad95a2c8)
