### ISSUE TITLE
Version tag 1.1.7, installing version 1.1.5

### ISSUE THREAD

**Issue by Doehl** [coreybutler/nvm-windows#374]
### My Environment

- [X] Windows 10

### Expected Behavior

Install version 1.1.7, when downloading setup file for 1.1.7.

### Actual Behavior

Version 1.1.5 is being installed instead.
The pc I have installed it on, have never had nvm installed before.

### Steps to reproduce the problem:

Download setup.exe for tag 1.1.7, and install.

**Comment by Doehl** [comment]
```
The system cannot find the path specified.
Your environment has been set up for using Node.js .

C:\Users\fckma\Documents\GitHub\nvm-test>nvm version
1.1.5
```

**Comment by hennzen** [comment]
I can confirm this behaviour on my Win10 machine. Did an install over an existing 1.1.3. Same for both nvm-noinstall.zip and nvm-setup.zip.

**Comment by Arcanemagus** [comment]
This is a duplicate of #375 (only because @coreybutler assigned themselves to that one instead of this 😉).

**Comment by coreybutler** [comment]
Apologies to all. This was due to a bad build. v1.1.7 has been updated in the releases (on 8/8/2018). I'm closing this since it should be resolved now. If anyone sees this behavior after this was posted, please open a new issue.

**Comment by treshugart** [comment]
I've tried the new setup link from the 1.1.7 tag and it's still installing 1.1.5 for me. I don't know how to install the `nosetup` version, so I haven't tried that.

A workaround for 1.1.5 not installing NPM is to set the `npm_mirror` to https://github.com/npm/cli/archive/.

**Comment by treshugart** [comment]
> A workaround for 1.1.5 not installing NPM is to set the npm_mirror to https://github.com/npm/cli/archive/.

NVM reports it as working, but it still doesn't seem to properly copy it over from `temp/` and `temp/` gets deleted before you can manually do it. This is quite frustrating.
