### ISSUE TITLE
NPM Path broken

### ISSUE THREAD

**Issue by rotexhawk** [coreybutler/nvm-windows#486]
If this is a question about how to use NVM4W, please use [stackoverflow](http://stackoverflow.com/questions/tagged/nvm-windows) instead.

If this is an issue regarding antivirus, make sure you search the existing issues first.

### My Environment

- [ ] Windows 7 or below (not truly supported due to EOL - see wiki for details)
- [ ] Windows 8
- [ ] Windows 8.1
- [ x] Windows 10
- [ ] Windows 10 IoT Core
- [ ] Windows Server 2012
- [ ] Windows Server 2012 R2
- [ ] Windows Server 2016

- [ ] My Windows installation is non-English.

### I'm using NVM4W version:

- [x ] 1.1.7
- [ ] 1.1.6
- [ ] 1.1.5
- [ ] 1.1.4
- [ ] 1.1.3
- [ ] 1.1.2
- [ ] 1.1.1
- [ ] Older
- [ ] OTHER (Please Specify)

### I have already...

- [ x] read the README to be aware of npm gotchas & antivirus issues.
- [x ] reviewed the [wiki](https://github.com/coreybutler/nvm-windows/wiki) to make sure my issue hasn't already been resolved.
- [ x] verified I'm using an account with administrative privileges.
- [x ] searched the issues (open and closed) to make sure this isn't a duplicate.
- [ x] made sure this isn't a question about how to use NVM for Windows, since [gitter](https://gitter.im/coreybutler/nvm-windows?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge) is used for questions and comments.

### Expected Behavior

nvm install 12.13.0 should install node and npm. It installs the node version but it can't install the npm version. I checked the path here https://github.com/coreybutler/nvm-windows/blob/master/src/nvm/web/web.go#L21 and it looks like we are still pointing to the incorrect npm url. Can we please fix this.

**Comment by C1one-38** [comment]
Are you sure you using `1.1.7`?

Because seems it was fixed in this version.

Or maybe you set `npm_mirror` parameter?

**Comment by coreybutler** [comment]
@C1one-38 is correct. The line being referenced is pointing to the appropriate URL. I also cannot recreate the issue, as shown here:

![image](https://user-images.githubusercontent.com/770982/69015245-cf1fe480-0957-11ea-948a-d259acd5b1a4.png)

I'm closing this since I do not believe the path is an issue. If you find a different issue causing this behavior, please open a new issue. 99% of the time, this issue occurs on new installations when people fail to uninstall Node before using NVM4W for the first time (as stated [here, in the README](https://github.com/coreybutler/nvm-windows#installation--upgrades)).

**Comment by rotexhawk** [comment]
I read the docs and removed every trace of node/npm but the problem still persists. nvm can install node and it actually creates the npm folder but the contents is always empty.

**Comment by rotexhawk** [comment]
@coreybutler This is still an issue. I just got a new laptop and installed the latest version of nvm. After that I installed node 12.18 but it still failed to install npm.
