### ISSUE TITLE
exit status 145: The directory is not empty , when I run command : nvm use 16.10.0 

### ISSUE THREAD

**Issue by tianberg** [coreybutler/nvm-windows#674]
**Issue:**

My computer info : 

OS : windows 10 
Terminal : PowerShell 

nvm-windows install directory :   **D:\apps\nvm-windows\nvm**

after install nvm-windows , check the nvm command location : 

`
PS D:\apps\nvm-windows\nvm\v12.18.2  get-command nvm

CommandType     Name                                               Version    Source

-----------     ----                                               -------    ------

Application     nvm.exe                                            0.0.0.0    D:\apps\nvm-windows\nvm\nvm.exe

`

check the current  nvm env :  

`
PS D:\apps\nvm-windows\nvm\v12.18.2   **nvm current**

v12.18.2
`

check the list command 

`
PS D:\apps\nvm-windows\nvm\v12.18.2 nvm list

16.10.0

12.18.2 (Currently using 64-bit executable)`

When switch to latest version : 16.10.0 

`
PS D:\apps\nvm-windows\nvm\v12.18.2         nvm use 16.10.0

exit status 145: The directory is not empty.
`

The error message " exit status 145: The directory is not empty. "  , is not clear meaning for which directory is not empty , because  the directory underline I running the  command " nvm use 16.10.0 "   , is a new directory and  is empty .

This is the first time I install nvm-windows on my  computer , windows 10 .

**Comment by coreybutler** [comment]
What directory is the `NVM_SYMLINK` environment variable set to?

**Comment by tianberg** [comment]
Thanks for help , 

My environment variable :   NVM_SYMLINK    is been set to :  D:\apps\nvm-windows    directory . 

I switch into   _D:\apps\nvm-windows_   , another error message show as below :  

`
cd D:\apps\nvm-windows

nvm use 16.10.0

exit status 32: The process cannot access the file because it is being used by another process.

`

Before  run above command , I restart my computer  , so no any  process use the  nvm  I think .

**Comment by coreybutler** [comment]
You don't need to switch to any particular directory to use the nvm.exe or node.exe files... NVM4W handles all the paths for you.

I suspect the reason you were originally unable to switch the version is because you ran the command from the same location that was being modified.

In other words, don't run `nvm use 16.10.0` when the console is using `D:\apps\nvm-windows\nvm\v12.18.2`. Instead, navigate to any other directory to run `nvm use x.x.x`. For example, open powershell or terminal and navigate to `:C\` or `D:\`, then run `nvm use 16.10.0`.

**Comment by tianberg** [comment]
The loop error happend , when I switch console directory to " any other directory " , such as : c:\  or  d:\

The error message happend as the my first post error  

**exit status 145: The directory is not empty.**

**Comment by chyen01** [comment]
I have the same problem too.

May I know what NVM_SYMLINK directory is recommended to set as?
Mine directed to the NodeJS automatically before installation. I change the drive from C to D since my NodeJS is installed in D.

**Comment by chyen01** [comment]
When I run 'nvm use 14.18.0' without it installed it says : 
**node v14.18.0 (64-bit) is not installed.**

Once I run 'nvm install 14.18.0', it went through smoothly. And there is 'v14.18.0' folder downloaded in the directory.

Then I run 'nvm use 14.18.0' and now it says:
**exit status 145: The directory is not empty.**

Not sure whats wrong here. I changed a few installation directory, avoided folder name with space and it is still the same problem.

**Comment by wuhou123** [comment]
me too,who can help me? this ques is so marry

**Comment by nobsessive** [comment]
I ran nvm setup program again and changed back to C:\Program Files for simulink location and it solved my problem. I'm using v1.1.8. It seems space doesn't affect v1.1.8, however you can't put simulink in an arbitrary folder.

**Comment by otamm** [comment]
I've just had this problem as well. It happens when the symlink is set to a path which contains whitespaces. Reinstalled nvm and set the symlink path to one without any whitespaces and everything is working as expected. The default suggested path begins is set to `C:\Program Files\nodejs` so I guess this problem must be very frequent now.

**Comment by almogoha** [comment]
For me the issue was "C:\Program Files (x86)\nodejs" folder was indeed non-empty after uninstalling nodejs.
Deleting that folder than "nvm use .." worked.

**Comment by ev-akarel** [comment]
@almogoha That worked for me too. Nice! Deleted the `C:\Program Files\nodejs` in my case.

**Comment by coreybutler** [comment]
The `This directory is not empty` issue was caused by an internal failure to remove any existing symlinks. This has been resolved in [v1.1.9](https://github.com/coreybutler/nvm-windows/releases/tag/1.1.9).

**Comment by fncolon** [comment]
> The `This directory is not empty` issue was caused by an internal failure to remove any existing symlinks. This has been resolved in [v1.1.9](https://github.com/coreybutler/nvm-windows/releases/tag/1.1.9).

<img width="282" alt="Capture" src="https://user-images.githubusercontent.com/50759463/146343660-9593b9c5-784e-4c97-8731-1d8a419cb6ce.PNG">

Still not resolved.

**Comment by coreybutler** [comment]
@fncolon if you have a prior version of Node installed, it can throw the same error (because NVM4W won't have permission to remove it). If the folder permissions are askew, you may need to manually remove the symlink before running `nvm use`.

**Comment by Forcex450** [comment]
1 - Uninstall the node js application from your computer
2 - If there is a `nodejs` file in the program files, delete it
3 - try and see.

**Comment by Forcex450** [comment]
> > The `This directory is not empty` issue was caused by an internal failure to remove any existing symlinks. This has been resolved in [v1.1.9](https://github.com/coreybutler/nvm-windows/releases/tag/1.1.9).
> 
> <img alt="Capture" width="282" src="https://user-images.githubusercontent.com/50759463/146343660-9593b9c5-784e-4c97-8731-1d8a419cb6ce.PNG">
> 
> Still not resolved.

1 - Uninstall the node js application from your computer
2 - If there is a `nodejs` file in the program files, delete it
3 - try and see.

**Comment by HemanthMavenir** [comment]
Uninstall any existing nodejs version and install using nvm install v.v.v

**Comment by andrewjhanlon** [comment]
On a Windows machine I simply navigated to C:\Program Files\nodejs\. I then renamed that folder to C:\Program Files\nodejsx\ (or anything else). After that I was able to run "nvm use v.v.v." to downgrade to the version of npm I needed. You can also just delete the folder but I opted to just rename it.
As a side-note, I'm on a 32-bit machine, so I needed to indicate that specifically in my use version command using this format:
"nvm use 16.14.0 32".

**Comment by Rainyforest** [comment]
> For me the issue was "C:\Program Files (x86)\nodejs" folder was indeed non-empty after uninstalling nodejs. Deleting that folder than "nvm use .." worked.

This is sooo helpful and it saved my night!!!

**Comment by andrewjhanlon** [comment]
My pleasure @Rainyforest! Glad that helped! :-)

**Comment by martingalvan-nordic** [comment]
@coreybutler this is still happening on 1.1.9. Even if it has to be solved manually, the error message should be changed to something more explicit.

**Comment by Abdurrahman-Alizada** [comment]
@andrewjhanlon Thanks. It helps me after changing the name of the node directory.

**Comment by petar-staynov** [comment]
I'm using version 1.1.9 and **I have solved this problem** by setting the Node.js Symling to a folder that  does not contain whitespaces. Default one is "C:\Program Files\nodejs" and contains a space. I've set mine to "C:\Users\user\AppData\Roaming\nvm\nodejs"

**Comment by jodik** [comment]
In my case renaming "C:\Program Files\nodejs" to "C:\Program Files\nodejs2" helped. Then nvm recreated "\nodejs" as simlink. Just as the error said "directory not empty" : )

**Comment by framerate** [comment]
@coreybutler it seems like this is still happening on 1.1.9 in my CI/CD pipeline (circle-ci) This is 1.19:
![image](https://user-images.githubusercontent.com/74291/173732269-bfc1985b-c64d-4e64-a86a-3c933ca5fb0c.png)

Just wanted to bring it to your attention since this issue was closed!

**Comment by hmadamk** [comment]
i solved the issue by uninstalling node from my pc then using nvm use v16.15.1 worked for me

**Comment by framerate** [comment]
@hmadamk Unfortunately I'm not sure that is an option for me as this is running on a pre-generated VM on my CI/CD provider's side. I'm still investigating, though. 

I do feel that `nvm use` should work regardless of my existing setup, but maybe @coreybutler has a reason this isn't the case. But it seemed like they thought it was an issue (and thought it was fixed!)

**Comment by coreybutler** [comment]
@framerate Node and NVM4W may conflict if both exist at the same time. When `node` or `node.exe` is called, Windows searches for the first executable found in the `PATH` environment variable. If a non-NVM Node installation path precedes the NVM4W symlink path in this variable, Windows will only use the non-NVM installation. This is just how Windows works.

There are two potential workarounds.

1. Rearrange the `PATH` to assure the NVM4W symlink comes before a common Node installation, because order matters.
1. Always use the full path to the NVM4W symlink root. For example, `C:\path\to\nvm_symlink\node.exe myscript.js`.

In the second option, it is safe to specify a hard-coded path because the NVM4W symlink will always point to the installation set whenever `nvm use ....` is run.

This is why the installer attempts to move pre-existing Node installations into the NVM4W directory. The problem is permissions. The NVM4W installer doesn't typically have permissions to uninstall a previous version of Node. This is why it's usually better to just uninstall Node before installing NVM4W.

**Comment by framerate** [comment]
Thank you @coreybutler. This proved a problem since I'm running this on a headless windows server, but in your defense almost EVERYTHING on a headless windows server is a nightmare ("just run the installer! just uninstall a program" haha)

I was able to move past this by removing files manually on the command line.

On an older version of circleci windows images that came with 1.1.7 I had to do this (in case it helps anyone else)

```
    - run:
          name: Install Proper Windows Build Tools (2017)
          command: |
            # Existing issue with NVM-windows 1.1.7
            # See https://github.com/npm/cli/issues/4234
            choco feature enable -n allowGlobalConfirmation
            choco install visualstudio2017buildtools visualstudio2017-workload-vctools
      - run:
          name: Check current version of NVM
          command: |
            # confirm NVM > 1.1.7 installed
            nvm --version  
      - run: |
          # see https://github.com/coreybutler/nvm-windows/issues/674#issuecomment-943523487
          rm -r "${NVM_SYMLINK}"
      - run: 
          name: nvm install 16.15.0
          command: |
            nvm install 16.15.0
            cd ../
            nvm use 16.15.0
            
```

Good luck future nerds!

**Comment by Liuwenjie88** [comment]
so many people meeting the question. Hope that the official to make improvement.

**Comment by Liuwenjie88** [comment]
@all  Friends, when you got **exit status 145: The directory is not empty.** Because you had install node.js.  If You wanted to resolve the question, please uninstall node.js first. Secondly,install nvm and then perform your steps you had performed.  
![安装成功](https://user-images.githubusercontent.com/51750162/178637788-6d360824-50db-4631-8b34-cc72bf106d84.png)

**Comment by Likaro-nav** [comment]
> For me the issue was "C:\Program Files (x86)\nodejs" folder was indeed non-empty after uninstalling nodejs. Deleting that folder than "nvm use .." worked.

It worked for me too 🥳 💘  
Since yesterday I'm with this error, and just deleted the nodejs folder solved it :)

**Comment by therisy** [comment]
> > Benim için sorun "C:\Program Files (x86)\nodejs" idi. Bu "vm kullan.." devam etmeye yaradı.
> 
> bende de işe yaradı🥳 💘 Dünden beri bu olmayacak ve düğümler klasörleri yeni sildim :)

how nice

**Comment by yosiasz** [comment]
Love this tool!

Cleaned up my pc short of a widows re-install ;) but still no go.

settings.txt says

root: D:\nvm
path: D:\nodejs

but it is installing node under d:\nvm

**Comment by budostylz** [comment]
I was able to uninstall and reinstall nvm. That fixed the problem for me.

**Comment by charles-dias** [comment]
@almogoha thank you. I forgot that I had an old NodeJs installation. So after delete the folder, everything work as expected.

**Comment by wlwl2** [comment]
> In my case renaming "C:\Program Files\nodejs" to "C:\Program Files\nodejs2" helped. Then nvm recreated "\nodejs" as simlink. Just as the error said "directory not empty" : )

Uninstalling from Apps and Features like @Jevin-0621 said and then deleting the folder like @jodik said solved the problem for me. Run the terminal (Powershell) **as administrator**.

**Comment by wuhou123** [comment]
已收到，谢谢

**Comment by BonnySAprnt** [comment]
This happened to me after deleting my node cache in app data and subsequently uninstalling/reinstalling node.js.

Reinstalling NVM fixed this.

**Comment by alexdominguess** [comment]
Guys, I just uninstalled everything, nodes(that was manually installed) and nvm (there is uninstall file for windows that will uninstall nmv and all the nod versions installed by the nvm and also will clear the env path)
Then I just reinstalled the nvm again, and installed all the nodes using the nvm tool. It worked for me.

**Comment by wuhou123** [comment]
已收到，谢谢

**Comment by maxi-test** [comment]
I have installed node manually then installed nvm. So I uninstalled node and then installed viw nvm. Problem solved

**Comment by nerexrs** [comment]
God may bless you all for sharing because this was pretty stressing since I am starting in app development so my WSL is not enough to support all the stuff that I need then I had to use normal windows an sheesh maybe they have good ui but the terminal is pretty crappy. There is another way to change my node version instead of delete node since in certains cases this could be dangerous?

**Comment by wuhou123** [comment]
已收到，谢谢

**Comment by coreybutler** [comment]
Since many people keep running into this, here are the important things to remember.

1. Read the README and [common issues](https://github.com/coreybutler/nvm-windows/wiki/Common-Issues#why-do-i-need-to-uninstall-nodejs-before-installing-nvm-for-windows). There's a reason the common issues are linked in the top part of the README. Most of these issues are easily avoidable if you follow the instructions.
1. Make sure you're running the [latest NVM4W](https://github.com/coreybutler/nvm-windows/releases).
1. Run `nvm debug`. It will catch a LOT of issues people tend to skip over and tell you how to correct them (99% of the time it's a user issue).
1. Review the [exit error common issue section](https://github.com/coreybutler/nvm-windows/wiki/Common-Issues#permissions-exit-1-exit-5-access-denied-exit-145).

Take note that we are building a new environment manager called [Runtime](https://github.com/coreybutler/nvm-windows/wiki/Runtime). Everything you currently get in NVM4W will be free in Runtime, but there will also be affordable commercial options with more features, support, and tools for enterprise/organizational users. We've spent a lot of time preparing this version to handle common issues (even user issues) seamlessly for a better experience.

I'm going to lock this issue since there are a lot of "me too" responses. Questions about this should be filed in the [discussions](https://github.com/coreybutler/nvm-windows/discussions).

---

**Side note: you don't _have_ to uninstall your original Node.js installation**

Since a few people have been concerned about deleting/uninstalling a prior version of Node before using NVM4W, you don't actually have to. You can make Windows "ignore" your original installation by putting NVM4W _before_ the original installation directory in your `PATH`. See [this section](https://github.com/coreybutler/nvm-windows/wiki/Common-Issues#why-do-i-need-to-uninstall-nodejs-before-installing-nvm-for-windows) for details. If you decide to remove NVM4W later, that version will work again.
