### ISSUE TITLE
exit status 1: Cannot create a file when that file already exists.

### ISSUE THREAD

**Issue by cfv1984** [coreybutler/nvm-windows#681]
**Issue:**

I accidentally ran nvm-noinstall before running the setup. After running the setup, I get ´exit status 1: Cannot create a file when that file already exists.´ as response after running `nvm on` or `nvm use $ANY_VERSION` where ANY_VERSION can be any of 10.14.0, 14.18 etc. 
I also get `exit status 5: Access is denied.` when running `nvm off`. 

**How To Reproduce:**

----------

⚠️ note ⚠️ : my PC is on an Azure Domain so my "local" admin user and my _used_ user differ. This means that if I run with admin privileges I run as my local admin, and it was this exact situation that caused me to fail at using `nvm-noinstall.zip`. 
I'm not entire sure this is relevant to the issue but since this was found to not be happening on an unrelated PC outside the domain I'm including it for completeness.

-----------
1. Download `https://github.com/coreybutler/nvm-windows/releases/download/1.1.8/nvm-noinstall.zip`
2. Run as instructed
3. This is the exact point where I noticed a configuration error on my part
3. Download `https://github.com/coreybutler/nvm-windows/releases/download/1.1.8/nvm-setup.zip`
4. Run as instructed
5. Notice errors after `nvm on` `nvm use` and `nvm off`

**Expected Behavior:**

NVM should work: I should be able to switch node versions without system errors

**Desktop:**
 - OS: Windows 10 Pro
 - Browser: Chrome, Firefox, Edge, Brave, Several IE versions on independent VMs too.

**Comment by TTSKarlsson** [comment]
I had this issue too after coming from a normal nodejs install, which I had uninstalled prior to installing nvm. I'm also running developer mode in Windows 11.

I noticed that my symlinked folder (`C:\nodejs`) was pointing an old version I didn't have, probably from me answering yes to "_14.15.5 version is already installed, do you want nvm to handle this version_" or something along those lines.

For me that version was installed by the emscripten sdk, and I didn't use it, but also didn't want to uninstall the sdk.

I could see what version by opening properties for the symlink folder, so I installed that version with `nvm install 14.15.5` and ran `nvm use 14.15.5` which then succeeded and I could then `nvm use 17.0.1` which I was aiming for to begin with.

**Comment by coreybutler** [comment]
Upon further investigation, I found this issue is ultimately caused by a pre-existing symlink that doesn't get recreated properly. This is fixed in master and will be released in v1.1.9 later this week.

**Comment by jlcarvalho** [comment]
I'm still having this issue with v1.1.9. I did something similar to https://github.com/coreybutler/nvm-windows/issues/681#issuecomment-963339632 when I installed the nvm.

**Comment by yogeshk25** [comment]
I was also facing same issue. For me, I opened cmd in admin mode. and then running `nvm use lts` worked.

**Comment by JunekCZ** [comment]
I found a folder (symlink) in the `C:/Program Files/nodejs `which was pointing to a non-existing version of node. I have deleted it and started `nvm use` command with the administrator right. Now everything works like a charm!

**Comment by LordFB** [comment]
type nvm on

**Comment by devdreamsolution** [comment]
@jlcarvalho , you should run the command as administrator
