### ISSUE TITLE
broken if username has space in it

### ISSUE THREAD

**Issue by kdpuvvadi** [coreybutler/nvm-windows#881]
**Issue:**

Most of the functionality is broken if the username has space in it, such as `on`, `off`, `use` and `uninstall`.  

**How To Reproduce:**
1. have space in username ( in one of my pcs, it's Kd Puvvadi)
2. Install `1.1.9` and upgrade to `1.1.10` or install `1.1.10`
3. run ` nvm use 16.18.1`

```
$ nvm use 16.18.1
exit status 1: 'C:\Users\Kd' is not recognized as an internal or external command,
operable program or batch file.

exit status 1: 'C:\Users\Kd' is not recognized as an internal or external command,
operable program or batch file.
```

```
nvm uninstall 16.16.0
Uninstalling node v16.16.0...exit status 1: 'C:\Users\Kd' is not recognized as an internal or external command,
operable program or batch file.
```

**Expected Behavior:**

When using `uninstall`, it should uninstall the version and when using `use` it should switch the version

**Desktop:**
 - OS: Windows 10 Enterprise 22H2 19045.2251 Windows Feature Experience Pack 120.2212.4180.0
 - Shell: Powershell Core

**Comment by kdpuvvadi** [comment]
Tested this on another installation, 

```
$ nvm install 16.18.0
Downloading node.js version 16.18.0 (64-bit)...
Extracting node and npm...
Complete
npm v8.19.2 installed successfully.

Installation complete. If you want to use this version, type
nvm use 16.18.0

$ nvm use 16.18.0
exit status 1: 'C:\Users\Sri' is not recognized as an internal or external command,
operable program or batch file.
```

**Comment by folmert** [comment]
Same here. It should be fixed, or at least mentioned in the docs.

**Comment by aderchox** [comment]
> Is this using an official installer or something else (like winget)? When 1.1.9 was released, there was a bug with spaces in paths. It was fixed within 2-3 days of the initial release, and a new binary was uploaded to the Github repo. However; many of the third party installers automatically pulled 1.1.9 the day it was released and never updated. These same tools failed to update to 1.1.10 properly.
> 
> A fresh [1.1.10 installation](https://github.com/coreybutler/nvm-windows/releases/tag/1.1.10) should work though.

I'm on version 1.1.10 and I still have the issue of having space in paths. E.g., when the path is in `D:\Program Files`:
> C:\Users\mojta> nvm use 16.18.1
> exit status 1: 'D:\Program' is not recognized as an internal or external command,
> operable program or batch file.

**Comment by kdpuvvadi** [comment]
> Is this using an official installer or something else (like winget)?

It's directly from this repo.

**Comment by pixelpax** [comment]
Yes, bump, still broken. Windows default is "fname lastname" iirc, so this should be a problem for most users

**Comment by Ethorsen** [comment]
Same issue if installation directory has a space in it.

ex.   c:\Program Files\nvm

**Comment by kdpuvvadi** [comment]
> Downgrading to 1.1.9 here from the repo worked

@khill-fbmc problem with downgrading is, switching version needs elevated privileges.

**Comment by kdpuvvadi** [comment]
> Given the choice between 1.1.10 that's totally broken and 1.1.9 that just needs elevated privileges... 🤷

All users in our network don't have elevated privileges, that would be deal breaker too.

**Comment by Ethorsen** [comment]
You can install latest version in  non-default location. This works for me.

ex.    c:/nvm

**Comment by HandyHat** [comment]
I think this is still an issue

**Comment by nintra** [comment]
Workaround: 
```
# display short names:
# e.g. Oliver Mustermann -> OLIVER~1
dir C:\Users /X

# update path 
nvm root C:\Users\<Directory Shortname>\AppData\Roaming\nvm
```
This works instantly.
I'm not sure if you manually need to update the NVM_HOME env vars in system properties. (search for: "environment")

**Comment by twsimpson** [comment]
Looks like the quotes around the arguments [here](https://github.com/coreybutler/nvm-windows/commit/68df36c97457ffe1db52877bc6707f93ba86ffbc#diff-c4d480f687d74c39997fc58e33d300c73cfb458321c2ab26c765772db70a679eR470) were removed, and that's what's causing the issue.
Maybe just you can just explicitly quote each argument in elevatedRun?

**Comment by thundR1** [comment]
## Fix for windows
Just run your cmd as administrator and it should work

**Comment by jason-ha** [comment]
> Workaround:
> 
> ```
> # display short names:
> # e.g. Oliver Mustermann -> OLIVER~1
> dir C:\Users /X
> 
> # update path 
> nvm root C:\Users\<Directory Shortname>\AppData\Roaming\nvm
> ```
> 
> This works instantly. I'm not sure if you manually need to update the NVM_HOME env vars in system properties. (search for: "environment")

Wah. Want to try the workaround with short path replacement for the case of `D:\Program Files\nvm` but `dir /X` has no entry.

```
D:\>dir /X PR*
...
08/03/2023  11:39 AM    <DIR>                       Program Files

D:\>dir /X C:\Pr*
...
08/03/2023  10:32 AM    <DIR>          PROGRA~1     Program Files
08/03/2023  10:31 AM    <DIR>          PROGRA~2     Program Files (x86)
```

Tried assuming `PROGRA~1` but `nvm root` complained. Also tried creating "D:\Program Files (x86)" to force a second similar name, but still no short name.

Still broken on 1.1.11 using default installer.

**Comment by mkolarevic** [comment]
This seems to be fixed with v1.1.12, no workarounds required.
